apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config # Has to be scheduler-config
  namespace: default # Has to be default
data:
  schedulerName: "ext-kube-sched"
  schedulerNamespace: "default"
  customMetrics: |
    []
  parameters: |
    {}