# scheduler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-kube-sched
  namespace: default
  labels:
    app: ext-kube-sched
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-kube-sched
  template:
    metadata:
      labels:
        app: ext-kube-sched
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: ext-kube-scheduler
        image: tarikkada/ext-kube-sched:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ext-kube-sched
spec:
  selector:
    app: ext-kube-sched
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
