apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config # Has to be scheduler-config
  namespace: default # Has to be default
data:
  schedulerName: "static-scheduler"
  schedulerNamespace: "default"
  customMetrics: |
    []
  parameters: |
    {"worker": 1}